### PR TITLE
Add templating icons i.e. handlebars and emblem

### PR DESCRIPTION
**Pull request by mrbernnz**

### CODE REVIEW

**Comment by ctf0** [comment]
what exactly u want to merge ??? because HB and emblem are already added

**Comment by mrbernnz** [comment]
Apologies, I meant to ask for a request for those icons. I do see HB, but my emblem files are still not shown. Are you using this icon that was provided to the project? 
https://github.com/machty/emblem.js/issues/174

-- 
Noel B. Sagaille
908-220-7625
noel.sagaille@gmail.com

**Comment by mrbernnz** [comment]
Apologies, I meant to ask for a request for those icons. I do see HB, but my emblem files are still not shown. Are you using this icon that was provided to the project? 
https://github.com/machty/emblem.js/issues/174

**Comment by ctf0** [comment]
okey, u can either add it ur self and send me a PR or send me the icons for the emblem and send me a file to test with.

**Comment by ctf0** [comment]
as this is more of a feature request, i'll close this,plz open an issue.

**Comment by mrbernnz** [comment]
I will, just trying to find the icon I saw someone design.

**Pull request closed without merging**
