### PR TITLE
Update yaml icon

### PR DESCRIPTION
**Pull request by simov**
Fixes https://github.com/ctf0/Seti_ST3/issues/276
icons

It's a wrench.
And the color is exactly the same as with the default gear icon `file_type_default.png`, I picked the color from there.

### CODE REVIEW

**Comment by ctf0** [comment]
can we change it to something more distinguish than a wrench which oftenly known for settings ?

**Comment by simov** [comment]
Wrench and Gear symbols are the most commonly used icons for settings/preferences/configuration to my knowledge. Also the symbol is easily distinguishable when it's a tiny icon.

I'll think about something better these days and I'll let you know if I come up with something.

As for the settings buttons - in the past few years the three horizontal lines become popular with mobile UIs, and most recently the three dots from the material design, used in chrome. Of course these are not suitable to use for file icon.

**Comment by simov** [comment]
Now when I think about it, the default gear icon could be just fine for .yml files as well. If you take a look at the above screenshot .eslintrc looks perfectly fine with that gear icon being a configuration file as well.

**Comment by simov** [comment]
icons2


@ctf0 tell me what do you think?

**Comment by ctf0** [comment]
another setting icon, how about just a Y icon ?

**Comment by ctf0** [comment]
but i think i can make that icon the default for any .config file, what u think ?

**Comment by simov** [comment]
Y would be nice only if it's not too distracting. My thinking is that these settings files like .yml and such are the least looked at. And the yml one is particularly tricky to find an icon for because this format does not have a logo.

For settings I think the `default` icon is actually pretty good - the gear icon next to .eslintrc in the above screenshot. And like I said earlier in this thread I would rather want to see the default icon for yml as well, unless there is a really better icon than that. I'll push the above icon here just in case you want to use it. At least the icon is not too distracting.

One more thing: If you take a look at .editorconfig file above the icon used is the most common icon used for `code` - the `</>` and the funny thing about it is that .editorconfig is an yml file as well, so no angle brackets there. So I guess all of this stuff is just highly opinionated, and at the very least the icon shouldn't be too distracting.

**Comment by ctf0** [comment]
actually the `.editorconfig` have that icon because it gets opened by a syntax that use this icon, so to change it either i explicitly define what icon should it use or we change the language that opens it.

**Comment by ctf0** [comment]
i would recommend installing https://packagecontrol.io/packages/ApplySyntax

**Comment by ctf0** [comment]
i have changed the yaml icon, check again.

**Comment by simov** [comment]
It's looking good I think.

**Pull request closed without merging**
