### PR TITLE
Added a more comprehensive readme line.

### PR DESCRIPTION
**Pull request by completit**

### CODE REVIEW

**Comment by ctf0** [comment]
the `Theme - Default` trick is not something that everyone have to do ,because the icons works without any interfering by the user side.

**Comment by mitchellpash** [comment]
I've never had to do the Theme - Default trick and I've installed SETI on Ubuntu, Mac, and PC versions.

**Comment by ctf0** [comment]
@mitchellpash thanx.

**Comment by completit** [comment]
Ok :+1: I got Sublime text 3 Build 3065 on Windows 7 x64 and I didn't have the folder automatically created... not everyone has the same settings.

**Comment by ctf0** [comment]
@completit u dont have to create the folders ,actually u shouldn't create them unless there is a reason for ,anyway try to clear the cache folder (don't forget to remove the Theme - Default/icons as well) and see if the problem still persist.

**Pull request closed without merging**
