### PR TITLE
Add light theme (Seti_lte branch)

### PR DESCRIPTION
**Pull request by MianSaleem**
I am adding new light theme. This will be useful for glossy displays :)
* Created new branch Seti_lte
* Added light theme
* Updated the readme file

### CODE REVIEW

**Comment by ctf0** [comment]
it seems that i cant merge branches from other repos, so i made a new one for you under `Lte` so please make a new PR to that new branch, and remove everything related to Seti and only add the files that `LTE` uses.

**Comment by MianSaleem** [comment]
Do you want me remove all the files from Seti_ST3 then add the modified and new files to Lte branch?

**Comment by MianSaleem** [comment]
Please check [MianSaleem/Seti_ST3/tree/Lte](https://github.com/MianSaleem/Seti_ST3/tree/Lte) I have removed all the files except readme.md and added new files as requested. If this is correct, please let me know so that I can create pull request.

Thank you

**Comment by ctf0** [comment]
yes exactly , just remove the lines for the seti stuff from the read me & rename the scheme file

**Comment by MianSaleem** [comment]
Please have a look at the branch again. I have updated the readme.md and renamed the scheme file

**Comment by ctf0** [comment]
great, could u also make a version for the `seti_original` aswell & add an option for having the active tab text italic instead of having it as a default

**Comment by MianSaleem** [comment]
I have change the active tab text as requested but not sure about making a version for the `seti_original` Can you please guide me?

**Comment by ctf0** [comment]
just change the color for the `seti_original` theme file as u did with the `seti` so the user can apply any theme he like instead of just sticking to the default one :+1:

**Comment by MianSaleem** [comment]
I am very sorry for being dumb. I am not good with Sublime Text themes, I just changed the theme files for me as I have grossy display. I see my shadow in dark backgrounds so can't really use dark theme. As I know, user can apply the theme by changing his settings. Can you please point me to the file where I need to change the color?

Thank you

**Comment by ctf0** [comment]
its okay, np, i will implement it later, just send me the PR :metal:

**Comment by MianSaleem** [comment]
Thank you

**Comment by MianSaleem** [comment]
:( I am sorry I have created the PR. Didn't read your 2nd line.

**Comment by ctf0** [comment]
its okay, its okay, leave it and update it when u pull the latest changes tmrw

**Pull request merged**
