### PR TITLE
Master

### PR DESCRIPTION
**Pull request by immanuelsun888**
1. New background for inactive tabs and tabset.
2.  Changed color for caret.

### CODE REVIEW

**Comment by ctf0** [comment]
many thanx, just wait for me i will update the theme with many new stuff, then i will add ur PR to avoid any conflicts.

also does all ur changes are related to `Ark` or have you changed any of the seti theme it self ?

**Comment by immanuelsun888** [comment]
I added the Ark theme with its own color theme. Modified two background images in the Main directory for the Ark theme. You can find the 4 files in the PR. 

Here are few screenshots: 
image
image
image

Don't know what to do with the README. Please do whatever if you have a use for the Ark theme. Appreciate your great job, it is my number one choice...:)

**Comment by ctf0** [comment]
perfect, but dont you prefer to release it as a separate theme instead which give u more control over what to add and what to remove ?, btw i have updated the php pref file to work with the new build of ST.

**Comment by immanuelsun888** [comment]
Will have try that later. Still learning to modify themes..:) Thank you for encouragement, though. Keep up your good work!!!

**Comment by ctf0** [comment]
sure np, if you need any help just ask me :), i will leave this for the time being and later if you still want to add it, i will be more than happy to do so :+1:

**Comment by immanuelsun888** [comment]
Thank you! I will ask your help when I have time to dig into this more...:)

Just added a new branch `Ark` in new PR. 
- Made the recent pull from yours
- Updated the color theme `Ark` for CSS. 
- Attached two screenshots in the comment area there.

Please feel free to use it whatever you see fit...:) I like the theme myself and am using now.

**Comment by ctf0** [comment]
excellent, i will close this PR and leave the other one.

**Pull request closed without merging**
