### PR TITLE
Better NPM icon

### PR DESCRIPTION
**Pull request by lucasmciruzzi**
Taking the favicon from the official NPM site, a better NPM icon.

### CODE REVIEW

**Comment by ctf0** [comment]
merged but to be honest i still like the old one more.

**Comment by lucasmciruzzi** [comment]
The thing is, in a regular screen (not a retina) the NPM logo looks blured because it isn't optimized for 16x16 size, but the favicon used in the NPM website looks sharp.

Still, if the users doesn't like the new icon, this can be reverted, so is not a big deal.

Thanks for merging!

**Comment by ctf0** [comment]
manually download the latest commit and check it now ,i fixed the blur

**Comment by lucasmciruzzi** [comment]
Great! It looks awesome. Thanks!

**Pull request merged**
